- name: variables
  hosts: localhost
  vars: #variable declaration 
    course: "Ansible"
    Tainer: "kalla"
    Duration: "120 hrs"
  tasks:
  - name: print information
    ansible.builtin.debug:
      msg: "Hi, we are learning {{course}} from trainer {{Trainer}}, Duration is {{Duration}}"
