-name: : variables
  hosts: localhost
  vars: #variable declaration 
    course: "Ansible"
    Tainer: "Sivakumar"
    Duration: "120 hrs"
  tasks:
  -name: print override information
    vars: #Task level variables
      course: "Devops"
  ansible.builtin.debug:
   msg: "Hi, we are learning {{course}} from trainer {{Trainer}}, Duration is {{Duration}}"

   -name: print information
     ansible.builtin.debug:
      msg: "Hi, we are learning {{course}} from trainer {{Trainer}}, Duration is {{Duration}}"
