name: data types
hosts: localhost
vars:
  Course: Devops with aws #string
  Tools:
  - Linux
  - Shell
  - Ansible
  Experience: #map or directory
    Devops: 3
    AWS: 2
    Docker: 1
  Realproject: true #boolean
tasks:
- name: print variables
  ansible.builtin.debug:
    msg: "course: {{Course}}, Tools covered: {{Tools}}, Experience is:{{Experience}}"
    


