- name: check number
  hosts: localhost
  vars_prompt:
  - name: numner
    prompt: please enter the number
    private: no
  tasks:
  - name: number is less than 10
    ansbile.builtin.debug:
      msg: "Given number {{number}} is less than 10"
    when: number < 10

  - name: number is greater or equal to 10
    ansible.builtin.debug:
      msg: "Given number {{number}} is greater  than 10"
    when: number >= 10


